### ISSUE TITLE
Add neutral coe

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#212]
The tricky part is to pass some `Up` or `neu` *under a binder*. The following seems to be the only solution if we want to reuse `IAbs`:
```
  | NCoeAtType of {dir : dir; univ : value; abs : neu_abs; el : value}

...

and neu_abs = neutral IAbs.abs
and neutral = NeuNode of {neu : neu; action : I.action}
```
However, this will lead to very ugly and clumsy code. What should we do?

**Comment by jonsterling** [comment]
Very good point! It might not be *too* bad though... I could try it out if you want.

**Comment by jonsterling** [comment]
By the way, one thing that kind of concerns me is that because dimension substitution is independent of the evaluator (i.e. all those things in `Domain.ml`), we don't have the ability to try out different implementations of substitution, such as those which (e.g.) after a suspended substitution gets too deep, we force it automatically (which is what Agda does for instance). On the other hand, when it inter-defined with the evaluator we seem to get into other problems architecturally. Not super relevant to this ticket, but I wanted to say it.

**Comment by jonsterling** [comment]
In #230, I implemented a very crappy version of this, in which I represent the "neutral abstraction" as an ordinary abstraction, and maintain the proper invariants by hand. I'm not sure what else to do for the moment.
