### ISSUE TITLE
coercing in Code-like type...?

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#237]
I don't know what this one is about.
```
import path

data unit where
| triv

data twonit where
| wrap [x : unit]

let Code (n : twonit) : type =
  elim n [ wrap n' => dim -> unit ]

let test (p : Path twonit (wrap triv) (wrap triv)) : dim -> unit =
  coe 0 1 (lam _ -> triv) in (lam i -> Code (p i))
```
raises
```
Encountered error:
    Tried to unleash ((up
                       (U kan 0)
                       (twonit.elim
                        <clo (U kan 0) & (up
                                          (twonit)<[i/i]>
                                          (@ p i)
                                          [[?i=0 ((wrap (triv   )  ))<[0/i] ∘ [i/i]>]
                                          [?i=1 ((wrap (triv   )  ))<[1/i] ∘ [i/i]>]])>
                        (@ p i)
                        [wrap
                         <clo (# <_> unit) & (up
                                              (twonit)<[i/i]>
                                              (@ p i)
                                              [[?i=0 ((wrap (triv   )  ))<[0/i] ∘ [i/i]>]
                                              [?i=1 ((wrap (triv   )  ))<[1/i] ∘ [i/i]>]])>])
                       [[?i=0 (# <_> unit )]
                       [?i=1 (# <_> unit )]]))<[%4732/i]> as extension type.
```
Defining `Code` as just `dim -> unit` without the `elim` undoes the bug, as does replacing `dim -> unit` with just `unit`.

**Comment by favonia** [comment]
Is this related to the lack of eta-expension?

**Comment by jonsterling** [comment]
@favonia  This one seems like a real bug... that exception really shouldn't happen. I'll play with it a bit.

**Comment by jonsterling** [comment]
I think I see partly what is going on, but I need to fiddle with it a bit to make sure my understanding is correct.

**Comment by jonsterling** [comment]
As a preview, let me say that I think this bug is caused by lack of #212.

**Comment by jonsterling** [comment]
Yes, what is happening is: to see that the whole `coe` is of extension type, we end checking `(@ coe x)`; the reason this happens has to do with my new typechecking algorithm, where negative neutrals are checked rather than inferred. Eventually, we do see that this was well-typed, but at some point in the process (during `infer_spine`), we run `ext_apply` on the value of this `coe`.

What happens next is:

1. In the semantic domain, the `coe` is (incorrectly) represented as one of those canonical `Coe` generators, but the body of the abstraction is not literally an extension type as expected, but instead a neutral (that elimination). 

2. When `ext_apply` hits a `Coe`, it anticipates that the body of the abstraction is an extension type, and then does extension-type-coercion.

What should happen instead is that the whole coercion needs to be neutral in the semantic domain (see #212), so the action of `ext_apply` would be to just wrap it in a new stack frame.

We can either implement #212 immediately, or I can fix this with a hack.

**Comment by jonsterling** [comment]
I've implemented a first attempt at neutral coercions; it's not as nice / abstract as I would like, but it works.
